### ISSUE TITLE
Icons in Dolphin don't display correctly while on 100% scaling.

### ISSUE THREAD

**Issue by brandonilester** [2O48/Kaze#4]
Icons on the Dolphin file manager do not display correctly on 100% scaling, but do on over 100%.

![image](https://github.com/2O48/Kaze/assets/134813350/40ff5acc-a3cb-4b5d-ac01-0adc3eba362e)

**Comment by 2O48** [comment]
It works fine on my device, maybe you can edit the icon manually?

**Comment by brandonilester** [comment]
This is happening on a KDE Neon virtual machine, your using Fedora?

**Comment by 2O48** [comment]
Sorry I didn't check the issues, you are right, this may be a bug in plasma, you can try to manually modify the icon to match the kaze theme

**Comment by rferris** [comment]
Maybe they are svg files to allow for the extra scaling. I'll see if I can have a look today

**Comment by Mel34** [comment]
@brandonilester is your issue ocurring on xorg or wayland session?

**Comment by brandonilester** [comment]
Wayland

**Comment by Lucolesco** [comment]
#5
